FROM node:20 AS build

WORKDIR /app

COPY clustering-frontend/package*.json ./
RUN npm ci

COPY clustering-frontend/ ./
RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80